/* UTILIZANDO O LIKE */

SELECT 
    NOME, SEXO
FROM
    TBL_CLIENTES
WHERE
    NOME LIKE '%E';
    

SELECT 
    CLI.ID,
    CONCAT(CLI.NOME, ' ', CLI.SOBRENOME) AS NOME_COMPLETO,
    CLI.SEXO,
    CLI.PESO,
    GROUP_CONCAT(TEL.NUMERO) AS TELEFONES
FROM
    TBL_CLIENTES AS CLI
        INNER JOIN
    TBL_TELEFONES AS TEL ON CLI.ID = TEL.ID_CLIENTE
WHERE
    CLI.ID IN (9 , 10)
GROUP BY ID , NOME , SOBRENOME , SEXO , PESO;

DROP DATABASE LOJA;


