CREATE SCHEMA IF NOT EXISTS `db_clientes`;

USE `db_clientes` ;

-- -----------------------------------------------------
-- Table `db_clientes`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_clientes`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sexo` ENUM('F', 'M') NOT NULL,
  `EMAIL` VARCHAR(50) NULL DEFAULT NULL,
  `CPF` VARCHAR(15) NULL,
  PRIMARY KEY (`idcliente`));


-- -----------------------------------------------------
-- Table `db_clientes`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_clientes`.`endereco` (
  `idendereco` INT NOT NULL AUTO_INCREMENT,
  `rua` VARCHAR(30) NOT NULL,
  `bairro` VARCHAR(30) NOT NULL,
  `cidade` VARCHAR(30) NOT NULL,
  `estado` CHAR(2) NOT NULL,
  `id_cliente` INT NOT NULL,
  PRIMARY KEY (`idendereco`),
  CONSTRAINT `fk_endereco_clientes`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `db_clientes`.`cliente` (`idcliente`));


-- -----------------------------------------------------
-- Table `db_clientes`.`telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_clientes`.`telefone` (
  `idtelefone` INT NOT NULL AUTO_INCREMENT,
  `tipo` ENUM('RES', 'COM', 'CEL') NOT NULL,
  `numero` VARCHAR(10) NOT NULL,
  `id_cliente` INT NOT NULL,
  PRIMARY KEY (`idtelefone`, `id_cliente`),
  CONSTRAINT `fk_telefones_clientes1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `db_clientes`.`cliente` (`idcliente`));
    
    
/* CADASTRO DE CLIENTES */
INSERT INTO CLIENTE VALUES(NULL,'FLAVIO','M','FLAVIO@IG.COM','4657765');
INSERT INTO CLIENTE VALUES(NULL,'ANDRE','M','ANDRE@GLOBO.COM','7687567');
INSERT INTO CLIENTE VALUES(NULL,'GIOVANA','F',NULL,'0876655');
INSERT INTO CLIENTE VALUES(NULL,'KARLA','M','KARLA@GMAIL.COM','545676778');
INSERT INTO CLIENTE VALUES(NULL,'DANIELE','M','DANIELE@GMAIL.COM','43536789');
INSERT INTO CLIENTE VALUES(NULL,'LORENA','M',NULL,'774557887');
INSERT INTO CLIENTE VALUES(NULL,'EDUARDO','M',NULL,'54376457');
INSERT INTO CLIENTE VALUES(NULL,'ANTONIO','F','ANTONIO@IG.COM','12436767');
INSERT INTO CLIENTE VALUES(NULL,'ANTONIO','M','ANTONIO@UOL.COM','3423565');
INSERT INTO CLIENTE VALUES(NULL,'ELAINE','M','ELAINE@GLOBO.COM','32567763');
INSERT INTO CLIENTE VALUES(NULL,'CARMEM','M','CARMEM@IG.COM','787832213');
INSERT INTO CLIENTE VALUES(NULL,'ADRIANA','F','ADRIANA@GMAIL.COM','88556942');
INSERT INTO CLIENTE VALUES(NULL,'JOICE','F','JOICE@GMAIL.COM','55412256');

/* CADASTRE UM ENDERECO PARA CADA CLIENTE */
INSERT INTO ENDERECO VALUES(NULL,'RUA GUEDES','CASCADURA','B. HORIZONTE','MG',9);
INSERT INTO ENDERECO VALUES(NULL,'RUA MAIA LACERDA','ESTACIO','RIO DE JANEIRO','RJ',10);
INSERT INTO ENDERECO VALUES(NULL,'RUA VISCONDESSA','CENTRO','RIO DE JANEIRO','RJ',1);
INSERT INTO ENDERECO VALUES(NULL,'RUA NELSON MANDELA','COPACABANA','RIO DE JANEIRO','RJ',2);
INSERT INTO ENDERECO VALUES(NULL,'RUA ARAUJO LIMA','CENTRO','VITORIA','ES',3);
INSERT INTO ENDERECO VALUES(NULL,'RUA CASTRO ALVES','LEBLON','RIO DE JANEIRO','RJ',4);
INSERT INTO ENDERECO VALUES(NULL,'AV CAPITAO ANTUNES','CENTRO','CURITIBA','PR',5);
INSERT INTO ENDERECO VALUES(NULL,'AV CARLOS BARROSO','JARDINS','SAO PAULO','SP',6);
INSERT INTO ENDERECO VALUES(NULL,'ALAMEDA SAMPAIO','BOM RETIRO','CURITIBA','PR',7);
INSERT INTO ENDERECO VALUES(NULL,'RUA DA LAPA','LAPA','SAO PAULO','SP',8);
INSERT INTO ENDERECO VALUES(NULL,'RUA GERONIMO','CENTRO','RIO DE JANEIRO','RJ',11);
INSERT INTO ENDERECO VALUES(NULL,'RUA GOMES FREIRE','CENTRO','RIO DE JANEIRO','RJ',12);
INSERT INTO ENDERECO VALUES(NULL,'RUA GOMES FREIRE','CENTRO','RIO DE JANEIRO','RJ',13);

/* CADASTRE TELEFONES PARA OS CLIENTES */
INSERT INTO TELEFONE VALUES(NULL,'RES','68976565',9);
INSERT INTO TELEFONE VALUES(NULL,'CEL','99656675',9);
INSERT INTO TELEFONE VALUES(NULL,'CEL','33567765',1);
INSERT INTO TELEFONE VALUES(NULL,'CEL','88668786',1);
INSERT INTO TELEFONE VALUES(NULL,'COM','55689654',1);
INSERT INTO TELEFONE VALUES(NULL,'COM','88687979',2);
INSERT INTO TELEFONE VALUES(NULL,'COM','88965676',3);
INSERT INTO TELEFONE VALUES(NULL,'CEL','89966809',5);
INSERT INTO TELEFONE VALUES(NULL,'COM','88679978',6);
INSERT INTO TELEFONE VALUES(NULL,'CEL','99655768',7);
INSERT INTO TELEFONE VALUES(NULL,'RES','89955665',8);
INSERT INTO TELEFONE VALUES(NULL,'RES','77455786',9);
INSERT INTO TELEFONE VALUES(NULL,'RES','89766554',9);
INSERT INTO TELEFONE VALUES(NULL,'RES','77755785',10);
INSERT INTO TELEFONE VALUES(NULL,'COM','44522578',10);

/*Criar view*/
CREATE VIEW `vw_clientes` AS
SELECT
	*
FROM
	cliente;
    
/*Selecionar uma view*/
SELECT * FROM vw_clientes;

/*Inserir dados em uma view*/
INSERT INTO vw_clientes VALUES (null, 'ANDREIA', 'F', 'andreia@gmail.com', '45855412589889');

/*Deletar View*/
DROP VIEW vw_clientes;

